language: python
python:
 - "2.7"
# command to install dependencies
install: "pip install --allow-all-external jsonpath --allow-unverified jsonpath -r requirements.txt"
script: periscope/test/runtests.py
